type Skill {
    id: ID!
    title: String!
    category: String!
    level: Int!
    imagePath: String
    is_featured: Boolean!
    createdAt: DateTime!
    updatedAt: DateTime!
}

type ProjectSkill {
    id: ID!
    title: String!
}

scalar DateTime
    @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Project {
    id: ID!
    title: String!
    shortDescription: String! @rename(attribute: "short_description")
    description: String!
    link: String!
    isFeatured: Boolean! @rename(attribute: "is_featured")
    skills: [ProjectSkill!]! @belongsToMany
    imagePath: String!
    createdAt: DateTime! @rename(attribute: "created_at")
    updatedAt: DateTime! @rename(attribute: "updated_at")
}

type ServerStats {
    cpuUsage: Float!
    currentTime: DateTime!
}

type Query {
    skills(first: Int!, page: Int!, is_featured: Boolean @where): [Skill!]!
        @paginate(type: "PAGINATOR")
        @cache(maxAge: 600)
    skillsSelect: [Skill!]! @all @cache(maxAge: 600)
    projects(first: Int!, page: Int!, is_featured: Boolean @where): [Project!]!
        @paginate(type: "PAGINATOR")
    serverStats: ServerStats!
        @field(resolver: "App\\GraphQL\\Queries\\ServerStats")
}

type Mutation {
    deleteSkill(id: ID! @whereKey): Skill @delete
    deleteProject(id: ID! @whereKey): Project @delete
}
